name: Antioch_App
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  firebase_core: 0.5.0
  firebase_analytics: 6.0.0
  firebase_messaging: 7.0.0
  firebase_auth: 0.18.0
  firebase_database: 4.0.0
  cloud_firestore: 0.14.0

  url_launcher: ^5.5.2
  vector_math: ^2.0.8
  # google_sign_in: 4.4.1
  apple_sign_in: 0.1.0

  rxdart: 0.23.1
  provider: 4.0.5
  font_awesome_flutter: 8.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/